import type { LevelDef } from '../core/level';

/** World 2 — Momentum. Height is speed; speed is distance — and danger. */
export const WORLD2: LevelDef[] = [
  {
    id: 'w2-1',
    name: 'Over the Edge',
    world: 2,
    size: [7, 3],
    start: { at: [0, 1, 2], rot: 0 },
    goal: { at: [6, 1, 0], rot: 0 },
    voids: [
      [3, 0],
      [3, 1],
      [3, 2],
    ],
    inventory: { ramp: 2, track: 4 },
    par: 4,
    challenge: { kind: 'time', seconds: 2.3 },
    intro: 'A rail can end in mid-air. A fast sphere flies across the gap and lands on what lies beyond.',
    hint: 'Slow spheres drop into the gap. Roll down a Slope first, then leave the edge with speed.',
    solution: [
      { type: 'ramp', at: [1, 1, 1], rot: 0 },
      { type: 'track', at: [2, 1, 1], rot: 0 },
      { type: 'track', at: [4, 1, 0], rot: 0 },
      { type: 'track', at: [5, 1, 0], rot: 0 },
    ],
  },
  {
    id: 'w2-2',
    name: 'The Shaft',
    world: 2,
    size: [5, 3],
    start: { at: [0, 1, 2], rot: 0 },
    goal: { at: [4, 1, 0], rot: 0 },
    inventory: { drop: 1, ramp: 2, track: 3 },
    par: 3,
    challenge: { kind: 'gentle', maxSpeed: 2.8 },
    intro: 'The Drop Shaft lowers the sphere two levels in one cell — and calms it down.',
    hint: 'Slopes arrive fast. For a gentle arrival, let the Drop Shaft do the descending.',
    solution: [
      { type: 'ramp', at: [1, 1, 1], rot: 0 },
      { type: 'ramp', at: [2, 1, 0], rot: 0 },
      { type: 'track', at: [3, 1, 0], rot: 0 },
    ],
    challengeSolution: [
      { type: 'drop', at: [1, 1, 0], rot: 0 },
      { type: 'track', at: [2, 1, 0], rot: 0 },
      { type: 'track', at: [3, 1, 0], rot: 0 },
    ],
  },
  {
    id: 'w2-3',
    name: 'Too Fast!',
    world: 2,
    size: [6, 5],
    start: { at: [0, 0, 3], rot: 0 },
    goal: { at: [5, 3, 0], rot: 1 },
    inventory: { ramp: 3, drop: 1, curve: 1, track: 4 },
    par: 7,
    challenge: { kind: 'gentle', maxSpeed: 2.8 },
    intro: 'Speed is power — until a Bend comes. Too fast, and the sphere flies off.',
    hint: 'Three Slopes in a row is too much speed for the Bend. A Drop Shaft keeps it calm.',
    solution: [
      { type: 'drop', at: [1, 0, 1], rot: 0 },
      { type: 'ramp', at: [2, 0, 0], rot: 0 },
      { type: 'track', at: [3, 0, 0], rot: 0 },
      { type: 'track', at: [4, 0, 0], rot: 0 },
      { type: 'curve', at: [5, 0, 0], rot: 0 },
      { type: 'track', at: [5, 1, 0], rot: 1 },
      { type: 'track', at: [5, 2, 0], rot: 1 },
    ],
    challengeSolution: [
      { type: 'ramp', at: [1, 0, 2], rot: 0 },
      { type: 'drop', at: [2, 0, 0], rot: 0 },
      { type: 'track', at: [3, 0, 0], rot: 0 },
      { type: 'track', at: [4, 0, 0], rot: 0 },
      { type: 'curve', at: [5, 0, 0], rot: 0 },
      { type: 'track', at: [5, 1, 0], rot: 1 },
      { type: 'track', at: [5, 2, 0], rot: 1 },
    ],
  },
  {
    id: 'w2-4',
    name: 'Kick It',
    world: 2,
    size: [8, 3],
    start: { at: [0, 1, 3], rot: 0 },
    goal: { at: [7, 1, 0], rot: 0 },
    voids: [
      [4, 0],
      [4, 1],
      [4, 2],
      [5, 0],
      [5, 1],
      [5, 2],
    ],
    inventory: { ramp: 3, kicker: 1, track: 3 },
    par: 5,
    challenge: { kind: 'shards' },
    shards: [[5, 1, 2]],
    intro: 'The Kicker flicks the sphere upward. The faster it arrives, the farther it flies.',
    hint: 'The gap is too wide to simply roll off. Build speed with Slopes, then hit the Kicker.',
    solution: [
      { type: 'ramp', at: [1, 1, 2], rot: 0 },
      { type: 'ramp', at: [2, 1, 1], rot: 0 },
      { type: 'kicker', at: [3, 1, 1], rot: 0 },
      { type: 'track', at: [6, 1, 0], rot: 0 },
    ],
  },
  {
    id: 'w2-5',
    name: 'Through the Valley',
    world: 2,
    size: [8, 4],
    start: { at: [0, 0, 3], rot: 0 },
    goal: { at: [7, 2, 2], rot: 0 },
    fixed: [
      { type: 'track', at: [4, 2, 0], rot: 0 },
      { type: 'block', at: [4, 2, 1], props: { height: 2 } },
      { type: 'block', at: [4, 0, 0], props: { height: 4 } },
      { type: 'block', at: [4, 1, 0], props: { height: 4 } },
      { type: 'block', at: [4, 3, 0], props: { height: 4 } },
    ],
    inventory: { ramp: 5, curve: 2, track: 3 },
    par: 8,
    challenge: { kind: 'time', seconds: 3.2 },
    intro: 'Dive under the wall and climb back out. Every level you drop is a level you can climb.',
    hint: 'Turn while you are still slow and high — a Bend at the bottom of a long dive throws the sphere off.',
    solution: [
      { type: 'ramp', at: [1, 0, 2], rot: 0 },
      { type: 'curve', at: [2, 0, 2], rot: 0 },
      { type: 'ramp', at: [2, 1, 1], rot: 1 },
      { type: 'curve', at: [2, 2, 1], rot: 2 },
      { type: 'ramp', at: [3, 2, 0], rot: 0 },
      { type: 'ramp', at: [5, 2, 0], rot: 2 },
      { type: 'ramp', at: [6, 2, 1], rot: 2 },
    ],
  },
  {
    id: 'w2-6',
    name: 'Ski Jump',
    world: 2,
    size: [11, 3],
    start: { at: [0, 1, 3], rot: 0 },
    goal: { at: [10, 1, 0], rot: 0 },
    voids: [
      [4, 0],
      [4, 1],
      [4, 2],
      [5, 0],
      [5, 1],
      [5, 2],
      [8, 0],
      [8, 1],
      [8, 2],
    ],
    inventory: { ramp: 3, kicker: 2, track: 4, drop: 1 },
    par: 7,
    challenge: { kind: 'shards' },
    shards: [
      [5, 1, 2],
      [8, 1, 1],
    ],
    intro: 'Two chasms. Keep enough speed after the first landing to clear the second.',
    hint: 'Landing on flat rail loses speed. Land on a downhill Slope and keep the momentum.',
    solution: [
      { type: 'ramp', at: [1, 1, 2], rot: 0 },
      { type: 'ramp', at: [2, 1, 1], rot: 0 },
      { type: 'kicker', at: [3, 1, 1], rot: 0 },
      { type: 'ramp', at: [6, 1, 0], rot: 0 },
      { type: 'kicker', at: [7, 1, 0], rot: 0 },
      { type: 'track', at: [9, 1, 0], rot: 0 },
    ],
  },
];
