import type { LevelDef } from '../core/level';

/**
 * World 1 — Foundations. Each level adds one idea:
 * rails → slopes → bends → height as energy → combining → building in 3D.
 */
export const WORLD1: LevelDef[] = [
  {
    id: 'w1-1',
    name: 'First Light',
    world: 1,
    size: [5, 3],
    start: { at: [0, 1, 0], rot: 0 },
    goal: { at: [4, 1, 0], rot: 0 },
    inventory: { track: 3 },
    par: 3,
    challenge: { kind: 'shards' },
    shards: [[2, 1, 0]],
    intro: 'Pick the Rail below and fill the glowing cells between START and GOAL.',
    hint: 'Select the Rail, then click each glowing cell. Press PLAY when the rails light up.',
    guide: true,
    solution: [
      { type: 'track', at: [1, 1, 0], rot: 0 },
      { type: 'track', at: [2, 1, 0], rot: 0 },
      { type: 'track', at: [3, 1, 0], rot: 0 },
    ],
  },
  {
    id: 'w1-2',
    name: 'Downhill',
    world: 1,
    size: [6, 3],
    start: { at: [0, 1, 1], rot: 0 },
    goal: { at: [4, 1, 0], rot: 0 },
    inventory: { track: 3, ramp: 1 },
    par: 3,
    challenge: { kind: 'time', seconds: 1.7 },
    intro: 'The goal sits lower than the start. A Slope carries the sphere down a level.',
    hint: 'Place the Slope right next to the start — rolling down early means more speed for longer.',
    solution: [
      { type: 'track', at: [1, 1, 1], rot: 0 },
      { type: 'track', at: [2, 1, 1], rot: 0 },
      { type: 'ramp', at: [3, 1, 0], rot: 0 },
    ],
    challengeSolution: [
      { type: 'ramp', at: [1, 1, 0], rot: 0 },
      { type: 'track', at: [2, 1, 0], rot: 0 },
      { type: 'track', at: [3, 1, 0], rot: 0 },
    ],
  },
  {
    id: 'w1-3',
    name: 'The Bend',
    world: 1,
    size: [5, 5],
    start: { at: [0, 0, 0], rot: 0 },
    goal: { at: [4, 3, 0], rot: 0 },
    fixed: [{ type: 'block', at: [2, 2, 0], props: { height: 2 } }],
    inventory: { track: 5, curve: 3 },
    par: 6,
    challenge: { kind: 'shards' },
    shards: [[3, 2, 0]],
    intro: 'Bends turn the sphere. Pieces snap onto the rail — rotate them (R or the ⟳ button) if needed.',
    hint: 'Two Bends make a staircase: turn south, roll, then turn east into the goal.',
    solution: [
      { type: 'curve', at: [1, 0, 0], rot: 0 },
      { type: 'track', at: [1, 1, 0], rot: 1 },
      { type: 'track', at: [1, 2, 0], rot: 1 },
      { type: 'curve', at: [1, 3, 0], rot: 2 },
      { type: 'track', at: [2, 3, 0], rot: 0 },
      { type: 'track', at: [3, 3, 0], rot: 0 },
    ],
    challengeSolution: [
      { type: 'track', at: [1, 0, 0], rot: 0 },
      { type: 'track', at: [2, 0, 0], rot: 0 },
      { type: 'curve', at: [3, 0, 0], rot: 0 },
      { type: 'track', at: [3, 1, 0], rot: 1 },
      { type: 'track', at: [3, 2, 0], rot: 1 },
      { type: 'curve', at: [3, 3, 0], rot: 2 },
    ],
  },
  {
    id: 'w1-4',
    name: 'Height Is Energy',
    world: 1,
    size: [6, 3],
    start: { at: [0, 1, 2], rot: 0 },
    goal: { at: [5, 1, 1], rot: 0 },
    inventory: { ramp: 3, track: 1 },
    par: 4,
    challenge: { kind: 'time', seconds: 1.85 },
    intro: 'The sphere can climb — but only with the speed it gathered rolling down.',
    hint: 'Roll down first, then climb. A sphere never rises higher than where it started.',
    solution: [
      { type: 'track', at: [1, 1, 2], rot: 0 },
      { type: 'ramp', at: [2, 1, 1], rot: 0 },
      { type: 'ramp', at: [3, 1, 0], rot: 0 },
      { type: 'ramp', at: [4, 1, 0], rot: 2 },
    ],
    challengeSolution: [
      { type: 'ramp', at: [1, 1, 1], rot: 0 },
      { type: 'ramp', at: [2, 1, 0], rot: 0 },
      { type: 'track', at: [3, 1, 0], rot: 0 },
      { type: 'ramp', at: [4, 1, 0], rot: 2 },
    ],
  },
  {
    id: 'w1-5',
    name: 'Grand Tour',
    world: 1,
    size: [6, 6],
    start: { at: [0, 0, 2], rot: 0 },
    goal: { at: [5, 5, 0], rot: 1 },
    fixed: [
      { type: 'block', at: [2, 2, 0], props: { height: 2 } },
      { type: 'block', at: [3, 2, 0], props: { height: 2 } },
      { type: 'block', at: [2, 3, 0], props: { height: 2 } },
      { type: 'block', at: [3, 3, 0], props: { height: 2 } },
    ],
    inventory: { track: 6, ramp: 2, curve: 3 },
    par: 9,
    challenge: { kind: 'time', seconds: 3.05 },
    intro: 'Put it all together: slopes for speed, bends to steer.',
    hint: 'Go down both levels early, then run along the edge of the board.',
    solution: [
      { type: 'track', at: [1, 0, 2], rot: 0 },
      { type: 'ramp', at: [2, 0, 1], rot: 0 },
      { type: 'track', at: [3, 0, 1], rot: 0 },
      { type: 'ramp', at: [4, 0, 0], rot: 0 },
      { type: 'curve', at: [5, 0, 0], rot: 0 },
      { type: 'track', at: [5, 1, 0], rot: 1 },
      { type: 'track', at: [5, 2, 0], rot: 1 },
      { type: 'track', at: [5, 3, 0], rot: 1 },
      { type: 'track', at: [5, 4, 0], rot: 1 },
    ],
    challengeSolution: [
      { type: 'ramp', at: [1, 0, 1], rot: 0 },
      { type: 'ramp', at: [2, 0, 0], rot: 0 },
      { type: 'track', at: [3, 0, 0], rot: 0 },
      { type: 'track', at: [4, 0, 0], rot: 0 },
      { type: 'curve', at: [5, 0, 0], rot: 0 },
      { type: 'track', at: [5, 1, 0], rot: 1 },
      { type: 'track', at: [5, 2, 0], rot: 1 },
      { type: 'track', at: [5, 3, 0], rot: 1 },
      { type: 'track', at: [5, 4, 0], rot: 1 },
    ],
  },
  {
    id: 'w1-6',
    name: 'Spiral Stair',
    world: 1,
    size: [3, 3],
    start: { at: [0, 0, 3], rot: 0 },
    goal: { at: [0, 2, 0], rot: 2 },
    fixed: [{ type: 'block', at: [1, 1, 0], props: { height: 4 } }],
    inventory: { ramp: 3, curve: 2, track: 2 },
    par: 5,
    challenge: { kind: 'avoid', type: 'track' },
    intro: 'Build upward, not just outward. Wind your way down the tower.',
    hint: 'Alternate Slopes and Bends around the pillar: down, turn, down, turn, down.',
    solution: [
      { type: 'ramp', at: [1, 0, 2], rot: 0 },
      { type: 'curve', at: [2, 0, 2], rot: 0 },
      { type: 'ramp', at: [2, 1, 1], rot: 1 },
      { type: 'curve', at: [2, 2, 1], rot: 1 },
      { type: 'ramp', at: [1, 2, 0], rot: 2 },
    ],
  },
];
