import type { LevelDef } from '../core/level';

/** World 3 — Machines. Boosters, brakes, switches, gates and timing. */
export const WORLD3: LevelDef[] = [
  {
    id: 'w3-1',
    name: 'Power Up',
    world: 3,
    size: [6, 3],
    start: { at: [0, 1, 0], rot: 0 },
    goal: { at: [5, 1, 2], rot: 0 },
    inventory: { booster: 1, ramp: 2, track: 2 },
    par: 5,
    challenge: { kind: 'pieces', max: 4 },
    intro: 'The goal is two levels up. A Booster adds the energy that height alone cannot.',
    hint: 'Boosters push only in the direction of their arrows. Place one before the climb.',
    solution: [
      { type: 'booster', at: [1, 1, 0], rot: 0 },
      { type: 'track', at: [2, 1, 0], rot: 0 },
      { type: 'ramp', at: [3, 1, 0], rot: 2 },
      { type: 'ramp', at: [4, 1, 1], rot: 2 },
    ],
  },
  {
    id: 'w3-2',
    name: 'Brake Check',
    world: 3,
    size: [7, 5],
    start: { at: [0, 0, 4], rot: 0 },
    goal: { at: [6, 3, 0], rot: 1 },
    inventory: { ramp: 4, brake: 1, curve: 1, track: 3 },
    par: 8,
    challenge: { kind: 'gentle', maxSpeed: 1.6 },
    intro: 'Four levels of Slope is a lot of speed. Brakes tame it before the Bend.',
    hint: 'A Brake slows the sphere to a safe speed. Put one somewhere before the Bend.',
    solution: [
      { type: 'ramp', at: [1, 0, 3], rot: 0 },
      { type: 'ramp', at: [2, 0, 2], rot: 0 },
      { type: 'ramp', at: [3, 0, 1], rot: 0 },
      { type: 'ramp', at: [4, 0, 0], rot: 0 },
      { type: 'brake', at: [5, 0, 0], rot: 0 },
      { type: 'curve', at: [6, 0, 0], rot: 0 },
      { type: 'track', at: [6, 1, 0], rot: 1 },
      { type: 'track', at: [6, 2, 0], rot: 1 },
    ],
  },
  {
    id: 'w3-3',
    name: 'Gatekeeper',
    world: 3,
    size: [6, 4],
    start: { at: [0, 0, 0], rot: 0 },
    goal: { at: [5, 0, 0], rot: 0 },
    fixed: [
      { type: 'gate', at: [4, 0, 0], rot: 0, props: { channel: 0, state: 0 } },
      { type: 'switch', at: [2, 2, 0], rot: 0, props: { channel: 0 } },
    ],
    inventory: { curve: 4, track: 4, booster: 1 },
    par: 6,
    challenge: { kind: 'time', seconds: 3.0 },
    intro: 'The gate is locked. Roll over the matching Switch first and it will open.',
    hint: 'Make a detour: down to the Switch, back up, and through the gate.',
    solution: [
      { type: 'curve', at: [1, 0, 0], rot: 0 },
      { type: 'track', at: [1, 1, 0], rot: 1 },
      { type: 'curve', at: [1, 2, 0], rot: 2 },
      { type: 'curve', at: [3, 2, 0], rot: 1 },
      { type: 'track', at: [3, 1, 0], rot: 1 },
      { type: 'curve', at: [3, 0, 0], rot: 3 },
    ],
    challengeSolution: [
      { type: 'curve', at: [1, 0, 0], rot: 0 },
      { type: 'booster', at: [1, 1, 0], rot: 1 },
      { type: 'curve', at: [1, 2, 0], rot: 2 },
      { type: 'curve', at: [3, 2, 0], rot: 1 },
      { type: 'track', at: [3, 1, 0], rot: 1 },
      { type: 'curve', at: [3, 0, 0], rot: 3 },
    ],
  },
  {
    id: 'w3-4',
    name: 'Railyard',
    world: 3,
    size: [5, 6],
    start: { at: [0, 0, 0], rot: 0 },
    goal: { at: [3, 4, 0], rot: 1 },
    fixed: [
      { type: 'splitter', at: [3, 2, 0], rot: 0, props: { channel: 1, state: 0 } },
      { type: 'switch', at: [1, 4, 0], rot: 1, props: { channel: 1 } },
      { type: 'track', at: [3, 3, 0], rot: 1 },
    ],
    voids: [[3, 1]],
    inventory: { curve: 4, track: 5, booster: 1 },
    par: 9,
    challenge: { kind: 'time', seconds: 4.0 },
    intro: 'Switches flip Splitters of the same colour too. Right now this one points into the void.',
    hint: 'Visit the Switch first, then come back around into the Splitter. Boost on the way down to the Switch — that is the fast route.',
    solution: [
      { type: 'curve', at: [1, 0, 0], rot: 0 },
      { type: 'booster', at: [1, 1, 0], rot: 1 },
      { type: 'track', at: [1, 2, 0], rot: 1 },
      { type: 'track', at: [1, 3, 0], rot: 1 },
      { type: 'curve', at: [1, 5, 0], rot: 2 },
      { type: 'curve', at: [2, 5, 0], rot: 1 },
      { type: 'track', at: [2, 4, 0], rot: 1 },
      { type: 'track', at: [2, 3, 0], rot: 1 },
      { type: 'curve', at: [2, 2, 0], rot: 3 },
    ],
  },
  {
    id: 'w3-5',
    name: 'On the Beat',
    world: 3,
    size: [7, 3],
    start: { at: [0, 1, 0], rot: 0 },
    goal: { at: [6, 1, 0], rot: 0 },
    fixed: [{ type: 'timer', at: [4, 1, 0], rot: 0, props: { period: 2, phase: 1 } }],
    inventory: { track: 3, booster: 1, brake: 1 },
    par: 4,
    challenge: { kind: 'time', seconds: 2.0 },
    intro: 'The Pulse Gate opens and closes on a steady beat. Arrive while it is open.',
    hint: 'Too late? Speed up with a Booster. Watch the ring around the gate — it shows the rhythm.',
    solution: [
      { type: 'track', at: [1, 1, 0], rot: 0 },
      { type: 'track', at: [2, 1, 0], rot: 0 },
      { type: 'booster', at: [3, 1, 0], rot: 0 },
      { type: 'brake', at: [5, 1, 0], rot: 0 },
    ],
    challengeSolution: [
      { type: 'track', at: [1, 1, 0], rot: 0 },
      { type: 'booster', at: [2, 1, 0], rot: 0 },
      { type: 'track', at: [3, 1, 0], rot: 0 },
      { type: 'track', at: [5, 1, 0], rot: 0 },
    ],
  },
  {
    id: 'w3-6',
    name: 'Two Keys',
    world: 3,
    size: [7, 6],
    start: { at: [0, 0, 0], rot: 0 },
    goal: { at: [6, 5, 0], rot: 0 },
    fixed: [
      { type: 'gate', at: [5, 5, 0], rot: 0, props: { channel: 0, state: 0 } },
      { type: 'gate', at: [4, 5, 0], rot: 0, props: { channel: 1, state: 0 } },
      { type: 'switch', at: [3, 0, 0], rot: 0, props: { channel: 0 } },
      { type: 'switch', at: [6, 2, 0], rot: 1, props: { channel: 1 } },
    ],
    inventory: { track: 8, curve: 4, booster: 2 },
    par: 12,
    challenge: { kind: 'time', seconds: 4.2 },
    intro: 'Two locks, two keys. The sphere has to visit both switches before the gates.',
    hint: 'Plan the whole loop before you build. Boosters keep a long route alive.',
    solution: [
      { type: 'booster', at: [1, 0, 0], rot: 0 },
      { type: 'track', at: [2, 0, 0], rot: 0 },
      { type: 'track', at: [4, 0, 0], rot: 0 },
      { type: 'track', at: [5, 0, 0], rot: 0 },
      { type: 'curve', at: [6, 0, 0], rot: 0 },
      { type: 'track', at: [6, 1, 0], rot: 1 },
      { type: 'curve', at: [6, 3, 0], rot: 1 },
      { type: 'track', at: [5, 3, 0], rot: 0 },
      { type: 'track', at: [4, 3, 0], rot: 0 },
      { type: 'curve', at: [3, 3, 0], rot: 3 },
      { type: 'track', at: [3, 4, 0], rot: 1 },
      { type: 'curve', at: [3, 5, 0], rot: 2 },
    ],
      challengeSolution: [
      { type: 'booster', at: [1, 0, 0], rot: 0 },
      { type: 'track', at: [2, 0, 0], rot: 0 },
      { type: 'track', at: [4, 0, 0], rot: 0 },
      { type: 'track', at: [5, 0, 0], rot: 0 },
      { type: 'curve', at: [6, 0, 0], rot: 0 },
      { type: 'track', at: [6, 1, 0], rot: 1 },
      { type: 'curve', at: [6, 3, 0], rot: 1 },
      { type: 'booster', at: [5, 3, 0], rot: 2 },
      { type: 'track', at: [4, 3, 0], rot: 0 },
      { type: 'curve', at: [3, 3, 0], rot: 3 },
      { type: 'track', at: [3, 4, 0], rot: 1 },
      { type: 'curve', at: [3, 5, 0], rot: 2 },
    ],
  },
];
