import type { LevelDef } from '../core/level';

const ring = (cx: number, cz: number): [number, number][] => {
  const out: [number, number][] = [];
  for (let x = cx - 1; x <= cx + 1; x++) for (let z = cz - 1; z <= cz + 1; z++) if (x !== cx || z !== cz) out.push([x, z]);
  return out;
};

/** World 4 — Energy. Portals, launchers, collectors and magnets. */
export const WORLD4: LevelDef[] = [
  {
    id: 'w4-1',
    name: 'Shortcut',
    world: 4,
    size: [7, 5],
    start: { at: [0, 2, 0], rot: 0 },
    goal: { at: [6, 2, 0], rot: 0 },
    fixed: [0, 1, 2, 3].map((z) => ({ type: 'block' as const, at: [3, z, 0] as [number, number, number], props: { height: 3 } })),
    inventory: { teleporter: 2, track: 5, curve: 4 },
    par: 9,
    challenge: { kind: 'pieces', max: 3 },
    intro: 'Portals come in pairs. Roll into one and the sphere leaves the other at the same speed.',
    hint: 'Place one Portal facing the start and its twin facing the goal, on the far side of the wall.',
    solution: [
      { type: 'curve', at: [1, 2, 0], rot: 0 },
      { type: 'track', at: [1, 3, 0], rot: 1 },
      { type: 'curve', at: [1, 4, 0], rot: 2 },
      { type: 'track', at: [2, 4, 0], rot: 0 },
      { type: 'track', at: [3, 4, 0], rot: 0 },
      { type: 'track', at: [4, 4, 0], rot: 0 },
      { type: 'curve', at: [5, 4, 0], rot: 1 },
      { type: 'track', at: [5, 3, 0], rot: 1 },
      { type: 'curve', at: [5, 2, 0], rot: 3 },
    ],
    challengeSolution: [
      { type: 'teleporter', at: [1, 2, 0], rot: 0 },
      { type: 'teleporter', at: [4, 2, 0], rot: 2 },
      { type: 'track', at: [5, 2, 0], rot: 0 },
    ],
  },
  {
    id: 'w4-2',
    name: 'Island',
    world: 4,
    size: [8, 8],
    start: { at: [0, 0, 0], rot: 0 },
    goal: { at: [4, 4, 0], rot: 1 },
    voids: ring(4, 4),
    inventory: { launcher: 1, track: 5, curve: 5 },
    par: 7,
    challenge: { kind: 'pieces', max: 5 },
    intro: 'The Launcher fires the sphere exactly three cells ahead. Follow the dotted arc.',
    hint: 'The goal funnel can catch the sphere straight out of the air. Line the Launcher up three cells away.',
    solution: [
      { type: 'curve', at: [1, 0, 0], rot: 0 },
      { type: 'track', at: [1, 1, 0], rot: 1 },
      { type: 'track', at: [1, 2, 0], rot: 1 },
      { type: 'curve', at: [1, 3, 0], rot: 1 },
      { type: 'curve', at: [0, 3, 0], rot: 3 },
      { type: 'curve', at: [0, 4, 0], rot: 2 },
      { type: 'launcher', at: [1, 4, 0], rot: 0 },
    ],
    challengeSolution: [
      { type: 'track', at: [1, 0, 0], rot: 0 },
      { type: 'track', at: [2, 0, 0], rot: 0 },
      { type: 'track', at: [3, 0, 0], rot: 0 },
      { type: 'curve', at: [4, 0, 0], rot: 0 },
      { type: 'launcher', at: [4, 1, 0], rot: 1 },
    ],
  },
  {
    id: 'w4-3',
    name: 'Freefall',
    world: 4,
    size: [6, 5],
    start: { at: [0, 1, 4], rot: 0 },
    goal: { at: [2, 4, 0], rot: 1 },
    inventory: { collector: 1, track: 3, ramp: 2, curve: 2 },
    par: 5,
    challenge: { kind: 'pieces', max: 3 },
    intro: 'Let it fall! A Collector catches a dropping sphere and rolls it out gently.',
    hint: 'Watch where the sphere lands when it rolls off the tower — that is where the Collector belongs.',
    solution: [
      { type: 'track', at: [1, 1, 4], rot: 0 },
      { type: 'collector', at: [3, 1, 0], rot: 1 },
      { type: 'track', at: [3, 2, 0], rot: 1 },
      { type: 'curve', at: [3, 3, 0], rot: 1 },
      { type: 'curve', at: [2, 3, 0], rot: 3 },
    ],
    challengeSolution: [
      { type: 'collector', at: [2, 1, 0], rot: 1 },
      { type: 'track', at: [2, 2, 0], rot: 1 },
      { type: 'track', at: [2, 3, 0], rot: 1 },
    ],
  },
  {
    id: 'w4-4',
    name: 'Attraction',
    world: 4,
    size: [7, 6],
    start: { at: [0, 0, 0], rot: 0 },
    goal: { at: [3, 5, 0], rot: 1 },
    fixed: [{ type: 'launcher', at: [1, 0, 0], rot: 0 }],
    voids: [
      [2, 0],
      [3, 0],
      [4, 0],
      [5, 0],
      [6, 0],
    ],
    inventory: { magnet: 1, track: 4, curve: 2 },
    par: 5,
    challenge: { kind: 'pieces', max: 4 },
    intro: 'Magnets grab a flying sphere and send it off in a new direction — at full speed.',
    hint: 'Put the Magnet beside the Launcher arc, close to where the sphere comes down.',
    solution: [
      { type: 'magnet', at: [3, 1, 0], rot: 1 },
      { type: 'track', at: [3, 2, 0], rot: 1 },
      { type: 'track', at: [3, 3, 0], rot: 1 },
      { type: 'track', at: [3, 4, 0], rot: 1 },
    ],
  },
  {
    id: 'w4-5',
    name: 'Down the Well',
    world: 4,
    size: [7, 5],
    start: { at: [0, 2, 4], rot: 0 },
    goal: { at: [6, 2, 0], rot: 0 },
    fixed: [0, 1, 2, 3, 4].map((z) => ({ type: 'block' as const, at: [3, z, 0] as [number, number, number], props: { height: 6 } })),
    inventory: { collector: 1, teleporter: 2, track: 3, curve: 2, ramp: 2 },
    par: 6,
    challenge: { kind: 'pieces', max: 4 },
    intro: 'A tall tower, a solid wall. Catch the fall, then take a shortcut through space.',
    hint: 'Collector first, then feed its output straight into a Portal.',
    solution: [
      { type: 'collector', at: [2, 2, 0], rot: 3 },
      { type: 'teleporter', at: [2, 1, 0], rot: 3 },
      { type: 'teleporter', at: [4, 2, 0], rot: 2 },
      { type: 'track', at: [5, 2, 0], rot: 0 },
    ],
  },
  {
    id: 'w4-6',
    name: 'Slingshot',
    world: 4,
    size: [8, 6],
    start: { at: [0, 1, 0], rot: 0 },
    goal: { at: [6, 5, 0], rot: 1 },
    fixed: [
      { type: 'block', at: [5, 3, 0], props: { height: 3 } },
      { type: 'block', at: [5, 4, 0], props: { height: 3 } },
      { type: 'block', at: [5, 5, 0], props: { height: 3 } },
      { type: 'block', at: [6, 3, 0], props: { height: 3 } },
      { type: 'block', at: [7, 3, 0], props: { height: 3 } },
    ],
    voids: [
      [3, 0],
      [3, 1],
      [4, 0],
      [4, 1],
      [5, 0],
      [5, 1],
      [6, 1],
    ],
    inventory: { launcher: 1, magnet: 1, teleporter: 2, track: 3, curve: 2 },
    par: 6,
    challenge: { kind: 'time', seconds: 3.0 },
    intro: 'Launch, grab, warp. Three machines, one throw.',
    hint: 'The Magnet can feed a Portal directly. Put the exit Portal inside the walled garden.',
    solution: [
      { type: 'track', at: [1, 1, 0], rot: 0 },
      { type: 'launcher', at: [2, 1, 0], rot: 0 },
      { type: 'magnet', at: [4, 2, 0], rot: 1 },
      { type: 'teleporter', at: [4, 3, 0], rot: 1 },
      { type: 'teleporter', at: [6, 4, 0], rot: 3 },
    ],
  },
];
