import type { Cell3, FixedDef, LevelDef } from '../core/level';

const wall = (x: number, zs: number[], height: number): FixedDef[] => zs.map((z) => ({ type: 'block', at: [x, z, 0] as Cell3, props: { height } }));

/** World 5 — Mastermind. Several mechanisms working together, few spare parts. */
export const WORLD5: LevelDef[] = [
  {
    id: 'w5-1',
    name: 'Clockwork',
    world: 5,
    size: [6, 5],
    start: { at: [0, 0, 0], rot: 0 },
    goal: { at: [5, 4, 0], rot: 0 },
    fixed: [
      { type: 'switch', at: [2, 0, 0], rot: 0, props: { channel: 0 } },
      { type: 'timer', at: [3, 4, 0], rot: 0, props: { period: 2.4, phase: 0.6 } },
      { type: 'gate', at: [4, 4, 0], rot: 0, props: { channel: 0, state: 0 } },
    ],
    inventory: { booster: 2, brake: 1, track: 6, curve: 4 },
    par: 11,
    challenge: { kind: 'avoid', type: 'brake' },
    intro: 'A key, a lock and a heartbeat. Unlock the gate, then arrive on the beat.',
    hint: 'The Pulse Gate is the last obstacle. Change your speed — or your route — to arrive while it is open.',
    solution: [
      { type: 'brake', at: [1, 0, 0], rot: 0 },
      { type: 'track', at: [3, 0, 0], rot: 0 },
      { type: 'booster', at: [4, 0, 0], rot: 0 },
      { type: 'curve', at: [5, 0, 0], rot: 0 },
      { type: 'track', at: [5, 1, 0], rot: 1 },
      { type: 'track', at: [5, 2, 0], rot: 1 },
      { type: 'curve', at: [5, 3, 0], rot: 1 },
      { type: 'track', at: [4, 3, 0], rot: 0 },
      { type: 'track', at: [3, 3, 0], rot: 0 },
      { type: 'curve', at: [2, 3, 0], rot: 3 },
      { type: 'curve', at: [2, 4, 0], rot: 2 },
    ],
    challengeSolution: [
      { type: 'track', at: [1, 0, 0], rot: 0 },
      { type: 'track', at: [3, 0, 0], rot: 0 },
      { type: 'track', at: [4, 0, 0], rot: 0 },
      { type: 'curve', at: [5, 0, 0], rot: 0 },
      { type: 'booster', at: [5, 1, 0], rot: 1 },
      { type: 'track', at: [5, 2, 0], rot: 1 },
      { type: 'curve', at: [5, 3, 0], rot: 1 },
      { type: 'track', at: [4, 3, 0], rot: 0 },
      { type: 'track', at: [3, 3, 0], rot: 0 },
      { type: 'curve', at: [2, 3, 0], rot: 3 },
      { type: 'curve', at: [2, 4, 0], rot: 2 },
    ],
  },
  {
    id: 'w5-2',
    name: 'Ascension',
    world: 5,
    size: [3, 3],
    start: { at: [0, 2, 0], rot: 0 },
    goal: { at: [1, 1, 2], rot: 0 },
    fixed: [{ type: 'block', at: [1, 1, 0], props: { height: 2 } }],
    inventory: { booster: 2, ramp: 2, curve: 4, track: 2 },
    par: 8,
    challenge: { kind: 'pieces', max: 7 },
    intro: 'The goal waits on top of the tower. Climb around it.',
    hint: 'One strong Booster at the bottom can carry the sphere up two Slopes if the turns are tight.',
    solution: [
      { type: 'booster', at: [1, 2, 0], rot: 0 },
      { type: 'curve', at: [2, 2, 0], rot: 1 },
      { type: 'ramp', at: [2, 1, 0], rot: 1 },
      { type: 'curve', at: [2, 0, 1], rot: 0 },
      { type: 'ramp', at: [1, 0, 1], rot: 0 },
      { type: 'curve', at: [0, 0, 2], rot: 3 },
      { type: 'curve', at: [0, 1, 2], rot: 2 },
    ],
  },
  {
    id: 'w5-3',
    name: 'Parallel Worlds',
    world: 5,
    size: [10, 5],
    start: { at: [0, 0, 0], rot: 0 },
    goal: { at: [9, 4, 2], rot: 0 },
    fixed: [
      ...wall(4, [0, 1, 2, 3, 4], 4),
      { type: 'switch', at: [1, 2, 0], rot: 1, props: { channel: 0 } },
      { type: 'gate', at: [6, 4, 0], rot: 0, props: { channel: 0, state: 0 } },
      { type: 'teleporter', at: [0, 4, 0], rot: 2 },
      { type: 'teleporter', at: [5, 4, 0], rot: 2 },
    ],
    inventory: { booster: 1, ramp: 2, track: 4, curve: 3 },
    par: 8,
    challenge: { kind: 'pieces', max: 6 },
    intro: 'The key is on this side of the wall. The lock is on the other.',
    hint: 'Portals keep the speed you bring. Boost before you warp, and climb on the far side.',
    solution: [
      { type: 'curve', at: [1, 0, 0], rot: 0 },
      { type: 'booster', at: [1, 1, 0], rot: 1 },
      { type: 'track', at: [1, 3, 0], rot: 1 },
      { type: 'curve', at: [1, 4, 0], rot: 1 },
      { type: 'ramp', at: [7, 4, 0], rot: 2 },
      { type: 'ramp', at: [8, 4, 1], rot: 2 },
    ],
  },
  {
    id: 'w5-4',
    name: 'Free Fall Express',
    world: 5,
    size: [8, 5],
    start: { at: [0, 2, 5], rot: 0 },
    goal: { at: [7, 2, 0], rot: 0 },
    voids: [
      [5, 0],
      [5, 1],
      [5, 2],
      [5, 3],
      [5, 4],
    ],
    inventory: { magnet: 1, collector: 1, kicker: 1, ramp: 2, track: 3, drop: 1 },
    par: 6,
    challenge: { kind: 'checkpoint' },
    checkpoint: [3, 2, 2],
    intro: 'Plunge from the top, catch it mid-air, and leap the chasm.',
    hint: 'A Magnet can grab the sphere while it is still falling — high up, where it still has somewhere to go.',
    solution: [
      { type: 'magnet', at: [2, 2, 2], rot: 0 },
      { type: 'ramp', at: [3, 2, 1], rot: 0 },
      { type: 'kicker', at: [4, 2, 1], rot: 0 },
      { type: 'track', at: [6, 2, 0], rot: 0 },
    ],
  },
  {
    id: 'w5-5',
    name: 'Loop the Loop',
    world: 5,
    size: [6, 5],
    start: { at: [2, 0, 0], rot: 1 },
    goal: { at: [4, 3, 0], rot: 1 },
    fixed: [
      { type: 'splitter', at: [2, 2, 0], rot: 2 },
      { type: 'splitter', at: [4, 2, 0], rot: 0, props: { channel: 2, state: 0 } },
      { type: 'switch', at: [4, 1, 0], rot: 1, props: { channel: 2 } },
    ],
    inventory: { booster: 1, track: 7, curve: 4 },
    par: 12,
    challenge: { kind: 'time', seconds: 6.5 },
    intro: 'The pink Splitter sends the sphere north, over its own Switch. Bring it back around for a second pass.',
    hint: 'The left Splitter works as a merge: whatever enters from above or below leaves to the east.',
    solution: [
      { type: 'track', at: [2, 1, 0], rot: 1 },
      { type: 'booster', at: [3, 2, 0], rot: 0 },
      { type: 'curve', at: [4, 0, 0], rot: 3 },
      { type: 'curve', at: [5, 0, 0], rot: 0 },
      { type: 'track', at: [5, 1, 0], rot: 1 },
      { type: 'track', at: [5, 2, 0], rot: 1 },
      { type: 'track', at: [5, 3, 0], rot: 1 },
      { type: 'curve', at: [5, 4, 0], rot: 1 },
      { type: 'track', at: [4, 4, 0], rot: 0 },
      { type: 'track', at: [3, 4, 0], rot: 0 },
      { type: 'curve', at: [2, 4, 0], rot: 2 },
      { type: 'track', at: [2, 3, 0], rot: 1 },
    ],
  },
  {
    id: 'w5-6',
    name: 'The Grand Machine',
    world: 5,
    size: [10, 8],
    start: { at: [0, 0, 4], rot: 0 },
    goal: { at: [8, 6, 0], rot: 0 },
    fixed: [
      { type: 'switch', at: [4, 0, 0], rot: 0, props: { channel: 0 } },
      { type: 'gate', at: [6, 6, 0], rot: 0, props: { channel: 0, state: 0 } },
      ...wall(1, [3, 4, 5], 2),
    ],
    voids: [[3, 3], [3, 4], [4, 3], [4, 4], [5, 3], [5, 4], [6, 3], [6, 4], [7, 3], [7, 4], [8, 3], [8, 4], [9, 3], [9, 4]],
    inventory: { drop: 1, ramp: 2, curve: 4, booster: 1, launcher: 1, track: 8, brake: 1 },
    par: 10,
    challenge: { kind: 'shards' },
    shards: [
      [5, 4, 1],
      [3, 0, 0],
    ],
    intro: 'Everything you have learned, in one machine. Tower, key, river, lock.',
    hint: 'Hit the key on the way down, then launch across the river toward the gate.',
    solution: [
      { type: 'drop', at: [1, 0, 2], rot: 0 },
      { type: 'ramp', at: [2, 0, 1], rot: 0 },
      { type: 'ramp', at: [3, 0, 0], rot: 0 },
      { type: 'curve', at: [5, 0, 0], rot: 0 },
      { type: 'booster', at: [5, 1, 0], rot: 1 },
      { type: 'launcher', at: [5, 2, 0], rot: 1 },
      { type: 'track', at: [5, 5, 0], rot: 1 },
      { type: 'curve', at: [5, 6, 0], rot: 2 },
      { type: 'track', at: [7, 6, 0], rot: 0 },
    ],
  },
];
